services:
  agent:
    build: .
    container_name: agent
    network_mode: "host"
    
    environment:
      - OLLAMA_HOST=192.168.178.23

    volumes:
      - ..:/project

    stdin_open: true
    tty: true